services:
  windrose:
    build:
      context: .
      args:
        WINE_FLAVOR: stable
    image: windrose-ds:dev
    pull_policy: never
    environment:
      UPDATE_ON_START: ${UPDATE_ON_START:-false}
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./healthcheck.sh:/healthcheck.sh:ro
      - ./scripts:/opt/windrose/scripts:ro
